name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  setup-verilator:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        compiler:
          - { cc: clang-17, cxx: clang++-17 }
    runs-on: ${{ matrix.os }}
    name: Verilator | ${{ matrix.os }} | ${{ matrix.compiler.cc }}
    env:
      CI_BUILD_STAGE_NAME: build
      CI_RUNS_ON: ${{ matrix.os }}
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
      VERILATOR_ARCHIVE: verilator-${{ matrix.os }}-${{ matrix.compiler.cc }}.tar.gz
    steps:

    - name: Cache Verilator
      id: cache
      uses: actions/cache@v4
      env:
        cache-name: verilator-cache-${{ matrix.os }}-${{ matrix.compiler.cc }}
      with:
        path: ${{ github.workspace }}/${{ env.VERILATOR_ARCHIVE }}
        key: verilator-cache-${{ matrix.os }}-${{ matrix.compiler.cc }}

    - name: Setup Clang 17
      if: steps.cache.outputs.cache-hit != 'true' && matrix.compiler.cc == 'clang-17'
      working-directory: ${{ github.workspace }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod u+x llvm.sh
        sudo ./llvm.sh 17

    - name: Build Verilator
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: |
        sudo apt-get install -y git help2man perl python3 make autoconf g++ flex bison clang
        sudo apt-get install -y libfl2  # Ubuntu only (ignore if gives error)
        sudo apt-get install -y libfl-dev  # Ubuntu only (ignore if gives error)
        sudo apt-get install -y zlib1g zlib1g-dev  # Ubuntu only (ignore if gives error)
        git clone https://github.com/verilator/verilator
        unset VERILATOR_ROOT
        cd verilator
        git checkout v5.020
        autoconf
        ./configure CC=${{ matrix.compiler.cc }} CXX=${{ matrix.compiler.cxx }} LINK=${{ matrix.compiler.cxx }}
        make -j4

    - name: Tar-up Verilator
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: tar -zcf ${{ env.VERILATOR_ARCHIVE }} verilator

  builtin-test:
    runs-on: ubuntu-22.04

    env:
      VERILATOR_ARCHIVE: verilator-ubuntu-22.04-clang-17.tar.gz

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache
        id: cache
        uses: coursier/cache-action@v6

      - name: Setup Clang 17
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 17

      - name: Fetch cached Verilator
        uses: actions/cache/restore@v4
        env:
          cache-name: verilator-cache-ubuntu-22.04-clang-17
        with:
          path: ${{ github.workspace }}/${{ env.VERILATOR_ARCHIVE }}
          key: verilator-cache-ubuntu-22.04-clang-17
          fail-on-cache-miss: true

      - name: Install Verilator
        working-directory: ${{ github.workspace }}
        run: |
          tar -zxf ${{ env.VERILATOR_ARCHIVE }}
          cd verilator
          sudo make install
          verilator --version

      - name: Setup Mill
        uses: zhutmost/setup-mill@main
        with:
          mill-version: 0.12.17

      - name: builtin-chiseltest
        run: |
          make test

      - name: Random Unit-Test
        run: |
          make clean
          make emu
          ./build/emu -O 10000
